id: 226b8ff8e3104ff9a9d4528dd52f78d2
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_504-Account_of_the_Previous_Aspirations_of_Bhaisajyaguruvaiduryaprabha-v2
  language: en
  author: ''
  volume: {}
